baseURL = "/"
languageCode = "en-us"
title = "AGX Site"
enableRobotsTXT = true

# Disable default Hugo taxonomy (we don't use them now)
disableKinds = ["taxonomy", "taxonomyTerm"]

# Pagination (new syntax)
[pagination]
  pagerSize = 12

[outputs]
  home = ["HTML", "RSS"]

[minify]
  disableXML = true

[module]
  [[module.imports]]
    path = "github.com/cuongpham0212/agx-mobile-theme"
